var mongoose = require('mongoose');  

var RecordSchema = new mongoose.Schema({  
    identyfikatorPRNG: { type: Number, min: 0, max: 10000000 },
    nazwaGłówna: String,
    rodzajObiektu: String,
    klasaObiektu: String,
    obiektNadrzędny: String,
    funkcjaAdministracyjna: String,
    dopełniacz: String,
    przymiotnik: String,
    uwagi: String,
    źródłoInformacji: String,
    elementRozróżniający: String,
    elementRodzajowy: String,
    wymowaIPA: String,
    wymowaPolska: String,
    szerokośćGeograficzna: String,
    długośćGeograficzna: String,
    współrzędneProstokątneY: { type: Number},
    współrzędneProstokątneX: { type: Number},
    dataModyfikacji: { type: Date, default: Date.now },
    rodzajReprezentacji: String,
    systemZewnętrzny: String,
    identyfikatorZewnętrzny: String,
    identyfikatorIIP: String,
    skalaMapy: String,
    statusNazwy: String,
    nazwaDodatkowa: String,
    kodJęzykaNazwyDodatkowej: String,
    językNazwyDodatkowej: String,
    latynizacjaNazwyDodatkowej: String,
    nazwaHistoryczna: String,
    nazwaOboczna: String,
    uwagiNazwDodatkowych: String,
    uwagiNazwHistorycznych: String,
    uwagiNazwObocznych: String,
    obcyEgzonim: String,
    pismoEgzonimu: String,
    językEgzonimu: String,
    latynizacjaEgzonimu: String,
    zagranicznyEndonim: String,
    pismoEndonimu: String,
    językEndonimu: String,
    latynizacjaEndonimu: String,
    państwo: String,
    województwo: String,
    powiat: String,
    gmina: String,
    identyfikatorJednostkiPodziałuTerytorialnegoKraju: { type: Number},
    dataWprowadzenia: { type: Date, default: Date.now },
    dataZniesieniaLubUsunięcia: String,
    przestrzeńNazw: String,
});

mongoose.model('Record', RecordSchema);
module.exports = mongoose.model('Record');

